name: release-pc

on:
  workflow_dispatch:
    inputs:
      version:
        description: "release version/tag"
        required: true
      packageManager:
        description: "pnpm@x.x.x"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-24.04
            kernel_path: "../app/kernel-linux/SiYuan-Kernel"
            build_args: "-s -w -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
            electron_args: "dist-linux"
            goos: "linux"
            goarch: "amd64"
            suffix: "linux.tar.gz"

    steps:
      - uses: actions/checkout@v4
        with:
          path: siyuan-note

      - name: clone origin and apply patches
        run: |
          mkdir -p ${{ github.workspace }}/go
          cd ${{ github.workspace }}/siyuan-note/

          git clone --branch ${{ github.event.inputs.version }} --depth=1 https://github.com/siyuan-note/siyuan.git
          cd siyuan

          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/disable-update.patch
          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/default-config.patch
          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/mock-vip-user.patch

          git status

      - name: Install rpm build dependencies
        if: contains( matrix.config.goos, 'linux')
        run: sudo apt-get update -qq && sudo apt-get install -y -qq rpm

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ${{ github.workspace }}/siyuan-note/siyuan/kernel/go.mod
          cache-dependency-path: ${{ github.workspace }}/siyuan-note/siyuan/kernel/go.sum
          cache: true
      - run: go version

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Node pnpm
        run: npm install -g ${{ github.event.inputs.packageManager }}
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app

      - name: Cache pnpm store
        uses: actions/cache@v5
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('app/pnpm-lock.yaml') }}
          restore-keys: pnpm-${{ runner.os }}-

      - name: Install Node Dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app

      - name: Building UI
        run: pnpm run build
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app

      - name: Building Kernel
        run: go build --tags fts5 -o "${{ matrix.config.kernel_path }}" -v -ldflags "${{ matrix.config.build_args }}"
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/kernel
        env:
          GO111MODULE: on
          CGO_ENABLED: 1
          GOOS: ${{ matrix.config.goos }}
          GOPATH: ${{ github.workspace }}/go
          GOARCH: ${{ matrix.config.goarch }}

      - name: Building Electron
        run: |
          # 添加 rpm 打包目标
          sed -i '/- target: "deb"/a\    - target: "rpm"' electron-builder-linux.yml
          pnpm run ${{ matrix.config.electron_args }}
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app

      - uses: joutvhu/get-release@v1
        id: get_current_release
        with:
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Electron App
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ github.workspace }}/siyuan-note/siyuan/app/build/siyuan-*-${{ matrix.config.suffix }}
          allowUpdates: true
          omitBody: true
          omitName: true
          tag: ${{ github.event.inputs.version }}
          replacesArtifacts: false

      - name: Upload Linux AppImage
        if: contains( matrix.config.goos, 'linux')
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ github.workspace }}/siyuan-note/siyuan/app/build/siyuan-*-linux.AppImage
          allowUpdates: true
          omitBody: true
          omitName: true
          tag: ${{ github.event.inputs.version }}
          replacesArtifacts: false

      - name: Upload Linux RPM
        if: contains( matrix.config.goos, 'linux')
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ github.workspace }}/siyuan-note/siyuan/app/build/siyuan-*-linux.rpm
          allowUpdates: true
          omitBody: true
          omitName: true
          tag: ${{ github.event.inputs.version }}
          replacesArtifacts: false
